### ISSUE TITLE
How can I effectively modify this template?

### ISSUE THREAD

**Issue by lucabarattini** [suyalcinkaya/onur.dev#33]
Hi @suyalcinkaya ,
Your template is wonderful but I was just wondering. How can I effectively modify it and implement it?
You have not released the permits to do so, right?
Looking forward to hearing from you, 
Best.

**Comment by suyalcinkaya** [comment]
Hi @lucabarattini, I am unable to share the Contentful structure. However, please feel free to make any necessary adjustments based on your needs.

**Comment by lucabarattini** [comment]
> Hi @lucabarattini, I am unable to share the Contentful structure. However, please feel free to make any necessary adjustments based on your needs.

Why? You can't share just an anonymized version?
